name: .NET Core Desktop (x64)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: Distance.sln
      Wap_Project_Directory: Distance
      Configuration: Release
      Platform: x64

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - uses: microsoft/setup-msbuild@v1.0.2

    - name: Execute unit tests
      run: dotnet test

    - name: nuget restore
      run: nuget restore "${{ env.Solution_Name }}"

    - name: msbuild
      run: msbuild "${{ env.Solution_Name }}" /t:Restore /p:Configuration=${{ env.Configuration }} /p:Platform=${{ env.Platform }}

    - run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path "${{ env.Wap_Project_Directory }}" -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - run: msbuild "${{ env.Wap_Project_Directory }}\${{ env.Wap_Project_Directory }}.csproj" /p:Configuration=${{ env.Configuration }} /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundle=Always /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }} /p:Platform=${{ env.Platform }}

    - run: Remove-Item -path "${{ env.Wap_Project_Directory }}\GitHubActionsWorkflow.pfx"

    - run: ls -R "${{ env.Wap_Project_Directory }}\bin\x64\Release\"

    - name: Archive build artifacts
      run: |
        $path = "${{ github.workspace }}\Distance\bin\x64\Release\"
        $destination = "${{ github.workspace }}\Distance.zip"
        Write-Host "Archiving path: $path"
        Compress-Archive -Path $path -DestinationPath $destination -ErrorAction Stop
        
